import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className="min-h-screen bg-gray-100 text-sm">
          <div
            className="
            max-w-100
            mx-auto
            bg-white
            shadow-lg
            min-h-screen
            tabular-nums      
          "
          >
            {children}
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
