/**
 * ==========================================
 * BIMA SWIFT - CORE DOMAIN TYPES
 * ==========================================
 * This file serves as the single source of truth for all data structures
 * used across the application (Engine, UI, and API).
 */

// ==========================================
// 1. ENGINE CONFIGURATION TYPES
// ==========================================

/** Defines how a premium is mathematically calculated. */
export type RateType = "FREE" | "FLAT" | "PERCENTAGE_BPS";

/** Defines the universal categories of optional coverages. */
export type RiderType =
  | "PVT"
  | "EXCESS_PROTECTOR"
  | "LOSS_OF_USE"
  | "PERSONAL_ACCIDENT"
  | "WINDSCREEN"
  | "NON_STANDARD_ACCESSORIES"
  | "EMERGENCY_MEDICAL_EXPENSES"
  | "ROAD_RESCUE"
  | "THEFT_FIRE_EXTENSIONS";

export interface RiderOption {
  id: string;
  label: string;
  premium: number;
}

/**
 * Defines a pricing tier for the basic comprehensive premium based on vehicle value.
 */
export interface RatingBand {
  /** The minimum vehicle value to qualify for this band (inclusive). */
  minVehicleValue: number;
  /** The maximum vehicle value to qualify for this band (inclusive). Next band MUST start at max + 1. */
  maxVehicleValue: number;
  /** The percentage rate expressed in Basis Points (bps). e.g., 450 = 4.5% */
  basicRateBps: number;
  /** The absolute minimum premium to charge in KES, even if the bps calculation is lower. */
  basicMinPremium: number;
}

/**
 * Defines a pricing tier for an optional rider based on vehicle value.
 */
export interface RiderBand {
  /** The minimum vehicle value to qualify for this band (inclusive). */
  minVehicleValue: number;
  /** The maximum vehicle value to qualify for this band (inclusive). */
  maxVehicleValue: number;
  /** Determines how the rateValue property should be interpreted by the engine. */
  rateType: RateType;
  /** If FREE: 0. If FLAT: KES amount. If PERCENTAGE_BPS: Basis points (e.g., 25 = 0.25%). */
  rateValue: number;
  /** The absolute minimum premium to charge in KES for this specific rider. */
  minPremium: number;
}

/**
 * Represents a single optional coverage rulebook specific to an insurer.
 */
export interface TieredRider {
  /** The unique identifier for this specific insurer's rider (e.g., "pioneer_pvt"). */
  id: string;
  /** The universal category this rider belongs to (used by the UI to group toggles). */
  type: RiderType;
  /** The human-readable name displayed to the agent in the UI. */
  name: string;
  /** Determines if the agent is allowed to uncheck this coverage. */
  isToggleable: boolean;
  /** The value-based pricing rules for this rider. */
  bands: RiderBand[];

  options?: RiderOption[];
  meta?: Record<string, unknown>;
}

/**
 * The master configuration record for a specific insurer's motor product.
 * Acts as the rulebook for the calculation engine.
 */
export interface InsuranceProduct {
  /** Unique ID for the product configuration. */
  id: string;
  /** Unique ID for the insurance company (e.g., "ins_pioneer"). */
  insurerId: string;
  /** The human-readable name of the insurance company. */
  insurerName: string;
  /** The name of the specific product (e.g., "Private Comprehensive"). */
  productName: string;
  /** The fallback flat rate charged if the vehicle is forced into Third Party Only (TPO). */
  tpoFlatPremium: number;
  /** The value-based rules for calculating the basic premium. */
  ratingBands: RatingBand[];
  /** The list of available optional coverages for this product. */
  riders: TieredRider[];
}

// ==========================================
// 2. ENGINE OUTPUT TYPES
// ==========================================

/**
 * Represents the final, calculated monetary value of a single rider.
 */
export interface CalculatedRider {
  /** The unique ID of the rider that was calculated. */
  id: string;
  /** The human-readable name of the rider. */
  name: string;
  /** The final calculated premium in KES. */
  premium: number;
}

/**
 * The final output payload generated by the calculation engine.
 * This is what gets saved to the database and displayed to the user.
 */
export interface QuoteBreakdown {
  /** The calculated base premium before riders and levies (in KES). */
  basicPremium: number;
  /** An array of all optional coverages the user selected, with their calculated prices. */
  calculatedRiders: CalculatedRider[];
  /** The sum of the basicPremium + all calculatedRiders (in KES). */
  grossPremium: number;
  /** Insurance Training Levy (in KES). */
  itl: number;
  /** Policyholders Compensation Fund (in KES). */
  phcf: number;
  /** Flat government stamp duty (in KES). */
  stampDuty: number;
  /** The final, exact amount the client must pay (in KES). */
  totalPayable: number;
}

// 1. Generic Wrapper
export interface ExplainedValue<TBreakdown> {
  value: number;
  breakdown: TBreakdown;
}

// 2. Specific Breakdowns
export interface BasicPremiumBreakdown {
  rateBps: number; 
  rawCalculation: number; 
  isMinPremiumApplied: boolean;
}

export interface RiderBreakdown {
  rateType: RateType | "OPTION_SELECTION"; 
  rateValue: number; 
  rawCalculation: number;
  isMinPremiumApplied: boolean;
}

export interface LevyBreakdown {
  rateType: "PERCENTAGE_BPS" | "FLAT";
  rateValue: number;
  rawCalculation: number;
}

// 3. Detailed Final Breakdown
export interface DetailedCalculatedRider {
  id: string;
  name: string;
  premium: ExplainedValue<RiderBreakdown>;
}

export interface GrossPremiumBreakdown {
  basicPremium: number;
  calculatedRiders: number;
}

export interface DetailedQuoteBreakdown {
  coverType?: "COMPREHENSIVE" | "TPO";
  vehicleValue?: number;
  basicPremium: ExplainedValue<BasicPremiumBreakdown>;
  calculatedRiders: DetailedCalculatedRider[];
  grossPremium: ExplainedValue<GrossPremiumBreakdown>;
  itl: ExplainedValue<LevyBreakdown>;
  phcf: ExplainedValue<LevyBreakdown>;
  stampDuty: ExplainedValue<LevyBreakdown>;
  totalPayable: number;
}